blogappyt/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired
from blogappyt.models import Post


class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Post')

blogappyt/main/views.py
from flask import Blueprint
from flask import render_template,flash,redirect,url_for,request,abort
from flask_login import current_user
from blogappyt import bcrypt,db, mail
from blogappyt.models import User,Post,Like_Post
from flask_mail import Message

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def index():
    # read from url ?page=1
    # request.args.get(arguement,default,type)
    page = request.args.get('page',1,type=int)
    post_likes = Like_Post.query.order_by(Like_Post.date_posted.desc()).all()
    all_post = Post.query.order_by(Post.date_posted.desc()).all()
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    print(type(Post.query.order_by(Post.date_posted.desc())))
    return render_template('index.html',posts = posts,post_likes = post_likes)

@main.route('/about')
def about():
    return render_template('about.html',title='About')

blogappyt/posts/views.py
from flask import Blueprint
from blogappyt.posts.forms import  PostForm
from flask import render_template,flash,redirect,url_for,request,abort
from flask_login import current_user
from blogappyt import bcrypt,db, mail
from blogappyt.models import User,Post,Like_Post
from flask_login import login_user,current_user,logout_user,login_required
import secrets
import os
from PIL import Image
from flask_mail import Message

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET','POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data,content = form.content.data,auther = current_user)
        db.session.add(post)
        db.session.commit()
        print('post_id:',post.id)
        post_liked = Like_Post(post_id = post.id,post_likes = post)
        db.session.add(post_liked)
        db.session.commit()
        flash('Your Blog is Posted...','success')
        return redirect(url_for('main.index'))

    return render_template('newpost.html',title ='Create Post',form=form,legend="New Post")

@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    post_liked = Like_Post.query.get_or_404(post_id)
    print(post_liked)
    return render_template('post.html',title = post.title,post=post,post_liked=post_liked)

@posts.route('/post/<int:post_id>/update',methods=['GET','POST'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if post.auther != current_user and current_user.role != 'admin':
        abort(403)    

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your Post has been updated...','success')
        return redirect(url_for('posts.post',post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    
    return render_template('newpost.html',title ='Update Post',form=form,legend="Update Post")



@posts.route('/post/<int:post_id>/delete',methods=['GET','POST'])
@login_required
def post_delete(post_id):
    post = Post.query.get_or_404(post_id)
    post_liked = Like_Post.query.get_or_404(post_id)
    if post.auther != current_user and current_user.role != 'admin':
        abort(403)
    db.session.delete(post)
    db.session.delete(post_liked)
    db.session.commit()
    flash('Your Post has been deleted...','success')
    return redirect(url_for('main.index'))


@posts.route('/likepost/<int:post_id>')
@login_required
def like_post(post_id):
    post_like_counter = Like_Post.query.filter_by(post_id = post_id).first()
    if post_like_counter:
        post_like_counter.like_counter += 1
        db.session.add(post_like_counter)
        db.session.commit()
        return redirect(request.referrer)

@posts.route('/dislikepost/<int:post_id>')
@login_required
def dislike_post(post_id):
    post_dislike_counter = Like_Post.query.filter_by(post_id = post_id).first()
    if post_dislike_counter:
        post_dislike_counter.dislike_counter += 1
        db.session.add(post_dislike_counter)
        db.session.commit()
        return redirect(request.referrer)

blogappyt/users/views.py
from flask import Blueprint,render_template,flash,redirect,url_for,request,abort
from blogappyt.users.forms import RegistrationForm, LoginForm, UpdateProfileForm, RequestResetForm, ResetpasswordForm
from blogappyt.users.utils import save_picture,password_reset_email
from flask_login import current_user
from blogappyt import bcrypt,db, mail
from blogappyt.models import User,Post,Like_Post
from flask_login import login_user,current_user,logout_user,login_required
import secrets
import os
from PIL import Image
from flask_mail import Message

users = Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email = form.email.data,password= hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Registartion Completed for {form.username.data}!','success')
        return redirect(url_for('users.login'))
    return render_template('registration.html',form=form,title = 'Registration')

@users.route('/login', methods =['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.rememberme.data)
            return redirect(url_for('main.index'))
        else:
            flash('Wrong Info given','danger')
    return render_template('login.html',form=form,title = 'LogIn')

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/profile', methods=['GET','POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        
        # Save Profile Pic
        if form.profilepic.data:
            profile_pic = save_picture(form.profilepic.data)
            current_user.profile_pic = profile_pic
        
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Profile Updated Successfully','success')
        return redirect(url_for('users.profile'))
    
    # Pre-fill the form
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    posts = Post.query.filter_by(auther = current_user)
    profile_pic = url_for('static',filename='profilepic/'+current_user.profile_pic)
    return render_template('profile.html',title ='Profile',profile_pic = profile_pic,form=form,posts=posts)


@users.route('/user/<int:user_id>')
def user_profile(user_id):
    page = request.args.get('page',1,type=int)
    user = User.query.get_or_404(user_id)
    posts = Post.query.filter_by(auther = user).order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    profile_pic = url_for('static',filename='profilepic/'+user.profile_pic)
    return render_template('user_profile.html',title = user.username,posts=posts,user=user,profile_pic=profile_pic)

@users.route('/reset_password', methods =['GET','POST'])
def request_reset():

    # User needs to be logged out in order to access this page
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user:
            password_reset_email(user)
            flash('A Mail has been sent to your email','success')
            return redirect(url_for('users.login'))
        else:
            flash('This Email is not registered....','warning')
    return render_template('request_reset_form.html',form=form,title = 'Reset Password')


@users.route('/reset_password/<token>', methods =['GET','POST'])
def reset_password(token):

    # User needs to be logged out in order to access this page
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Token is invalid or expired please try agian....','warning')
        return redirect(url_for('users.request_reset'))
    form = ResetpasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your Password has been updated....','success')
        return redirect(url_for('users.login'))
   
    return render_template('reset_password.html',form=form,title = 'Reset Password')


@users.route('/admin/register',methods = ['GET','POST'])
def admin_register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,email = form.email.data,password= hashed_password)
        user.role = 'admin'
        db.session.add(user)
        db.session.commit()
        flash(f'Registartion Completed for {form.username.data}!','success')
        return redirect(url_for('users.login'))
    return render_template('registration.html',form=form,title = 'Admin_Registration')

blogappyt/templates/about.html
{% extends 'layout.html' %}
{% block content %}
<h1>about</h1>

{% endblock content %}

blogappyt/templates/index.html
{% extends 'layout.html' %}
{% block content %}
{% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{url_for('static',filename='profilepic/'+post.auther.profile_pic)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_profile',user_id=post.auther.id)}}">{{ post.auther.username }}</a>
              <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            {% if post.auther == current_user or current_user.role == 'admin'%}
            <div>
            <a class="btn btn-secondary btn-sm m-1" href="{{url_for('posts.post_update',post_id=post.id)}}">Update</a>
            <a  class="btn btn-danger btn-sm m-1" href="{{url_for('posts.post_delete',post_id=post.id)}}">Delete</a>
            </div>
            {% endif %}

            <h2><a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            <a class="btn btn-outline-info btn-sm m-1" href="{{url_for('posts.like_post',post_id=post.id)}}">Like</a><b class="text-primary"> {{post_likes[loop.index0].like_counter}}</b>
            <a class="btn btn-outline-danger btn-sm m-1" href="{{url_for('posts.dislike_post',post_id=post.id)}}">Dislike</a><b class="text-danger">{{post_likes[loop.index0].dislike_counter}}</b>
          </div>
        </article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
  {% if  page_num %}
    {% if  posts.page == page_num %}
      <a class = "btn btn-info mb-4" href="{{url_for('main.index',page = page_num)}}">{{page_num}}</a>
    {% else %}
    <a class = "btn btn-outline-info mb-4" href="{{url_for('main.index',page = page_num)}}">{{page_num}}</a>
    {% endif %}
  {% else %}
  {% endif %}
{% endfor %}
{% endblock content %}

blogappyt/templates/layout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
    {% block head %}
    {% if title %}
    <title>Flash Blog-{{title}}</title>
    {% else %}
    <title>Flash Blog</title>
    {% endif %}
    {% endblock head %}
    
</head>
<body>
    <header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('main.index')}}">Flask-Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('main.index')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.about')}}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('posts.create_post')}}">NewPost</a>
              </li>
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li> -->
            </ul>
            <div class="navbar-nav">
            {% if  current_user.is_authenticated%}
            <a class="nav-item nav-link" href="{{ url_for('users.profile') }}">Welcome, {{current_user.username|title}}</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
              </div>
          </div>
        </div>
      </nav>
</header>
<main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
      {% with  messages =  get_flashed_messages(with_categories = True) %}
        {% if messages %}
            {% for category,message in messages %}
            <div class='alert alert-{{category}}'>
            {{message}}</div>
            {% endfor %}
        {% endif %}
      {% endwith %}
        {% block content %}{% endblock %}
      </div>
      
    </div>
  </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

{% block javascript %}
{% endblock javascript%}
</body>
</html>

blogappyt/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
          
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-check mt-2 ml-2">
                {{ form.rememberme(class = "form-check-input")}}
                {{ form.rememberme.label(class = "form-check-label")}}
            </div>
        </fieldset>
        <div class="form-group mt-3">
            {{form.submit(class="btn btn-outline-info")}}
            <small class="text-muted ml-2">
            <a href="{{url_for('users.request_reset')}}">Forgot Password?</a>
        </small>
        </div>
        
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">Don't have an account?<a class="ml-2" href="{{url_for('users.register')}}">Sign up</a></small>
</div>
{% endblock content %}

blogappyt/templates/newpost.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>
          
            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.content.label(class="form-control-label")}}
                {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group mt-3">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>


{% endblock content %}

blogappyt/templates/post.html
{% extends 'layout.html' %}
{% block content %}

<article class="media content-section">
  <img class="rounded-circle article-img" src="{{url_for('static',filename='profilepic/'+post.auther.profile_pic)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.auther.username }}</a>
              <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            {% if post.auther == current_user %}
            <div>
            <a class="btn btn-secondary btn-sm m-1" href="{{url_for('posts.post_update',post_id=post.id)}}">Update</a>
            <a  class="btn btn-danger btn-sm m-1" href="{{url_for('posts.post_delete',post_id=post.id)}}">Delete</a>
            </div>
            {% endif %}
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
          <a class="btn btn-outline-info btn-sm m-1" href="{{url_for('posts.like_post',post_id=post.id)}}">Like</a><b class="text-primary">{{post_liked.like_counter }}</b>
            <a class="btn btn-outline-danger btn-sm m-1" href="{{url_for('posts.dislike_post',post_id=post.id)}}">Dislike</a><b class="text-danger">{{post_liked.dislike_counter }}</b>
        </article>

{% endblock content %}

blogappyt/templates/profile.html
{% extends 'layout.html' %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static',filename='profile.css')}}">
{% endblock head %}
{% block content %}
<div class="content-section">
    <div class="mdeia">
        <img class="rounded-circle account-img" src="{{profile_pic}}" alt="nopic">
        <div class="media-body">
            <h2 class="account-heading">{{current_user.username}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
        </div>
    </div>

    
        <form action="" method="POST" enctype="multipart/form-data" id='update_form'>
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Profile</legend>
                <div class="form-group">
                    {{form.username.label(class="form-control-label")}}
                    {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{form.profilepic.label()}}
                    {{form.profilepic(class="form-control-file")}}
                    {% if form.profilepic.errors %}
                    {% for error in form.profilepic.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group mt-3">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
       
    
</div>

<div class="content-section">
    <div class="mdeia">
    {% for post in posts %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{url_for('static',filename='profilepic/'+post.auther.profile_pic)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.auther.username }}</a>
              <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            {% if post.auther == current_user %}
            <div>
            <a class="btn btn-secondary btn-sm m-1" href="{{url_for('posts.post_update',post_id=post.id)}}">Update</a>
            <a  class="btn btn-danger btn-sm m-1" href="{{url_for('posts.post_delete',post_id=post.id)}}">Delete</a>
            </div>
            {% endif %}

            <h2><a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
{% endfor %}
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script src="{{url_for('static',filename='profile.js')}}"></script>
{% endblock javascript%}

blogappyt/templates/registration.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{form.hidden_tag()}}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.confirmpassword.label(class="form-control-label")}}
                {% if form.confirmpassword.errors %}
                        {{ form.confirmpassword(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirmpassword.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirmpassword(class="form-control form-control-lg") }}
                    {% endif %}
            </div>
        </fieldset>
        <div class="form-group mt-3">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">Already have account?<a class="ml-2" href="{{url_for('users.login')}}">Log in</a></small>
</div>
{% endblock content %}

blogappyt/templates/sidebar.html
<div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>

blogappyt/templates/user_profile.html
{% extends 'layout.html' %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static',filename='profile.css')}}">
{% endblock head %}
{% block content %}
{% if current_user.role == 'admin'%}
<div class="content-section">
    <div class="mdeia">
        <img class="rounded-circle account-img" src="{{profile_pic}}" alt="nopic">
        <div class="media-body">
            <h2 class="account-heading">{{user.username}}</h2>
            <p class="text-secondary">{{user.email}}</p>
        </div>
        <a class="btn btn-warning ml-4" href="#">Deactivate</a>
        <a class="btn btn-danger ml-4" href="#">Delete</a>
    </div>
    </div>
{% endif %}
    
<h1 class="account-heading">Posts by: {{user.username}}</h1>
<div class="content-section"> 

    <div class="mdeia">
    {% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{url_for('static',filename='profilepic/'+post.auther.profile_pic)}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.auther.username }}</a>
              <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            {% if post.auther == current_user %}
            <div>
            <a class="btn btn-secondary btn-sm m-1" href="{{url_for('posts.post_update',post_id=post.id)}}">Update</a>
            <a  class="btn btn-danger btn-sm m-1" href="{{url_for('posts.post_delete',post_id=post.id)}}">Delete</a>
            </div>
            {% endif %}

            <h2><a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
{% endfor %}
    </div>
</div>

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2) %}
  {% if  page_num %}
    {% if  posts.page == page_num %}
      <a class = "btn btn-info mb-4" href="{{url_for('users.user_profile',user_id=user.id,page = page_num)}}">{{page_num}}</a>
    {% else %}
    <a class = "btn btn-outline-info mb-4" href="{{url_for('users.user_profile',user_id=user.id,page = page_num)}}">{{page_num}}</a>
    {% endif %}
  {% else %}
  {% endif %}
{% endfor %}

{% endblock content %}